// Invalid division error

function main(in: ) out : no {
    integer a = "haha"/3;

}

/*
    assert(throw(InvalidDivisionError))
*/