// Invalid division error

function start(in: ) out : no {
    integer a = "haha"/3;

}

/*
    assert(throw(InvalidDivisionError))
*/